name: simple_app
description: A new Flutter project.


publish_to: 'none' 













version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  # hooks and state management
  flutter_hooks: ^0.18.5+1
  hooks_riverpod: ^2.1.1

  # local cache
  shared_preferences: ^2.0.15
  flutter_secure_storage: ^6.1.0
  floor: ^1.3.0
  form_field_validator: ^1.1.0
  floor_generator: ^1.3.0

  # Http client
  dio: ^4.0.6
  pretty_dio_logger: ^1.1.1
  searchfield: ^0.7.2

  internet_connection_checker: ^1.0.0+1
  connectivity_plus: any

  # utilities
  intl: ^0.18.0
  dartz: ^0.10.1
  path_provider: ^2.0.11
  path: ^1.8.2

  # routing and navigation
  auto_route: ^5.0.4

  # serialization
  json_annotation: ^4.7.0

  # data and union classes
  freezed_annotation: ^2.2.0
  
  cupertino_icons: ^1.0.2

  # uuid generator
  uuid: ^3.0.7

  xml: ^6.1.0
  url_launcher: ^6.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  auto_route_generator: ^5.0.2
  json_serializable: ^6.4.0
  freezed: ^2.1.0+1
  build_runner: ^2.2.1

flutter:
  uses-material-design: true

  
